# Gemini Code Assist Configuration
# Optimized for learning-focused, iterative code reviews

# General behavior
have_fun: false

# Code review configuration
code_review:
  # Enable code reviews
  disable: false

  # Focus on high-impact issues first (CRITICAL, HIGH, MEDIUM, LOW)
  # HIGH threshold ensures we get important issues without overwhelming feedback
  comment_severity_threshold: HIGH

  # Limit review comments to manageable chunks for iterative learning
  # 8-10 comments per review allows focused implementation without overwhelm
  max_review_comments: 10

# Pull request opened behavior
pull_request_opened:
  # Disable automatic help messages to reduce noise
  help: false

  # Enable PR summaries for context understanding
  summary: true

  # Enable automatic code reviews
  code_review: true

# File patterns to ignore during reviews
ignore_patterns:
  # Build and distribution files
  - 'dist/**'
  - 'build/**'
  - '.svelte-kit/**'
  - 'coverage/**'

  # Dependencies
  - 'node_modules/**'
  - 'pnpm-lock.yaml'
  - 'package-lock.json'
  - 'yarn.lock'

  # Generated files
  - '*.min.js'
  - '*.min.css'
  - '*.map'

  # Configuration files that rarely need review
  - '.env*'
  - '.gitignore'
  - '.prettierrc*'
  - '.eslintrc*'

  # Auto-generated documentation
  - 'CHANGELOG.md'
  - '*.generated.*'

  # Test coverage reports
  - 'coverage.json'
  - 'lcov.info'

# Additional settings for educational reviews
review_style:
  # Encourage explanatory feedback over simple corrections
  educational_focus: true

  # Prioritize high-impact suggestions over minor style issues
  impact_over_style: true

  # Provide context and examples when possible
  include_examples: true
