# .github/workflows/seo-post-deployment.yml
name: SEO Post-Deployment Validation

on:
  deployment_status:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to validate'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - preview

permissions:
  contents: read
  issues: write

jobs:
  run-reusable-seo-check:
    name: Run Reusable SEO Check
    uses: ./.github/workflows/reusable-seo-check.yml
    # Always run the reusable workflow for deployment events
    if: github.event_name == 'workflow_dispatch' || github.event.deployment_status.state == 'success'

  handle-results:
    name: Handle SEO Results
    needs: run-reusable-seo-check
    runs-on: ubuntu-latest
    if: always() && (github.event_name == 'workflow_dispatch' || github.event.deployment_status.state == 'success')

    steps:
      - name: Download SEO reports
        uses: actions/download-artifact@v4.1.8
        with:
          name: seo-reports-${{ github.run_id }}
          path: .seo-reports

      - name: Create Issue on SEO Failure
        if: needs.run-reusable-seo-check.outputs.exit_code != '0'
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const script = require('./.github/scripts/create-seo-issue.js');
            await script({github, context});
        env:
          ENVIRONMENT_INPUT: ${{ github.event.inputs.environment }}

      - name: Close SEO Issue on Success
        if: needs.run-reusable-seo-check.outputs.exit_code == '0'
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const script = require('./.github/scripts/close-seo-issue.js');
            await script({github, context});

      - name: Post Success Summary
        if: needs.run-reusable-seo-check.outputs.exit_code == '0'
        run: |
          echo "## ✅ Post-Deployment SEO Validation Passed!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All SEO validations passed after deployment. The site is SEO-compliant!" >> $GITHUB_STEP_SUMMARY