# .github/workflows/seo-validation.yml
name: SEO Validation

on:
  push:
    branches: [main, develop]
    paths:
      - 'posts/**'
      - 'about/**'
      - 'src/routes/**'
      - 'src/lib/**'
      - 'src/app.html'
      - 'static/robots.txt'
      - 'scripts/seo-validation.js'
  pull_request:
    branches: [main, develop]
    paths:
      - 'src/routes/**'
      - 'src/lib/**'
      - 'src/app.html'
      - 'static/robots.txt'
      - 'scripts/seo-validation.js'
      - 'svelte.config.js'
      - 'vite.config.js'
      - 'tailwind.config.js'
  workflow_dispatch:
    inputs:
      validate_all:
        description: 'Force validate all pages (even if no content changes)'
        required: false
        default: false
        type: boolean
      environment:
        description: 'Environment to validate'
        required: false
        default: 'production'
        type: choice
        options:
          - production
          - development

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write # For commenting on PRs
  issues: write # Fallback for github-script if needed

jobs:
  run-reusable-seo-check:
    name: Run Reusable SEO Check
    uses: ./.github/workflows/reusable-seo-check.yml

  handle-results:
    name: Handle SEO Results
    needs: run-reusable-seo-check
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download SEO reports
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.run-reusable-seo-check.outputs.artifact_name }}
          path: .seo-reports

      - name: Checkout Repository (for scripts)
        uses: actions/checkout@v4.2.2

      - name: Generate SEO Summary
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const script = require('./.github/scripts/generate-seo-summary.js');
            await script({core});
        env:
          EVENT_NAME: ${{ github.event_name }}
          ENVIRONMENT_INPUT: ${{ github.event.inputs.environment }}
          VALIDATE_ALL_INPUT: ${{ github.event.inputs.validate_all }}

      - name: Comment PR with SEO Results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const script = require('./.github/scripts/comment-pr-with-seo-results.js');
            await script({github, context});
        env:
          RUN_NUMBER: ${{ needs.run-reusable-seo-check.outputs.run_number }}
