# .github/workflows/seo-post-deployment.yml
name: SEO Post-Deployment Validation

on:
  deployment_status:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to validate'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - preview

permissions:
  contents: read
  issues: write

jobs:
  run-seo-validation:
    name: Run Post-Deployment SEO Validation
    uses: ./.github/workflows/reusable-seo-check.yml
    if: github.event_name == 'workflow_dispatch' || github.event.deployment_status.state == 'success'
    with:
      event_name: ${{ github.event_name }}
      environment: ${{ github.event.inputs.environment || 'production' }}
      deployment_url: ${{ github.event.deployment_status.environment_url || github.event.inputs.environment == 'production' && 'https://blog.nanggo.net' || 'https://preview.blog.nanggo.net' }}
