# .github/workflows/seo-validation.yml
name: SEO Validation

on:
  push:
    branches: [main, develop]
    paths:
      - 'posts/**'
      - 'about/**'
      - 'src/routes/**'
      - 'src/lib/**'
      - 'src/app.html'
      - 'static/robots.txt'
      - 'scripts/seo-validation.js'
  pull_request:
    branches: [main, develop]
    paths:
      - 'src/routes/**'
      - 'src/lib/**'
      - 'src/app.html'
      - 'static/robots.txt'
      - 'scripts/seo-validation.js'
      - 'svelte.config.js'
      - 'vite.config.js'
      - 'tailwind.config.js'
  workflow_dispatch:
    inputs:
      validate_all:
        description: 'Force validate all pages (even if no content changes)'
        required: false
        default: false
        type: boolean
      environment:
        description: 'Environment to validate'
        required: false
        default: 'production'
        type: choice
        options:
          - production
          - development

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write # For commenting on PRs
  issues: write # Fallback for github-script if needed

jobs:
  run-seo-validation:
    name: Run SEO Validation
    uses: ./.github/workflows/reusable-seo-check.yml
    with:
      event_name: ${{ github.event_name }}
      environment: ${{ github.event.inputs.environment || 'production' }}
      validate_all: ${{ github.event.inputs.validate_all || false }}
